name: Fist CI project
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - name: Use Node.Js version 16
        uses: action/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run build --prefix client

